permalink: /:year-:month-:day/:title
markdown: rdiscount
exclude: ["README.md", "CNAME", "LICENSE"]

title : Minute Labs
description : "Experiments with Interactive Visualization"
social :
  email : info@minutelabs.io
  github : minute-labs-io
  twitter : minutelabsio
limits :
  posts : 20

nav:
  - title: Labs
    url: /labs

  - title: About
    url: /about

  - title: Code
    url: /code

  - title: Subscribe
    url: /subscribe


