permalink: /:year-:month-:day/:title
markdown: rdiscount
exclude: ["README.md", "CNAME", "LICENSE"]

title : MinuteLabs.io
url : http://minutelabs.io
description : "Experiments in Interactive Explanations"
social :
  email : info@minutelabs.io
  github : minutelabsio
  twitter : minutelabsio
limits :
  posts : nil

nav:
  - title: Labs
    url: /labs

  - title: Subscribe
    url: /subscribe

  - title: About
    url: /about

  - title: Code
    url: /code

  - title: Store
    url: http://dftba.com/artist/60/MinutePhysics


