permalink: /:year-:month-:day/:title
markdown: kramdown
permalink: pretty #just for dev
exclude:
  - "README.md"
  - "CNAME"
  - "LICENSE"
  - "package.json"
  - "node_modules"
  - "src"
  - "vendor" #jekyll travis

title : MinuteLabs.io
url : http://labs.minutelabs.io
description : "Cool science shown through a combination different media"
version: "0.0.5"
library_path: "/library"

social :
  email : info@minutelabs.io
  github : minutelabsio
  twitter : minutelabsio

limits :
  posts : nil

nav:
  - title: Labs
    url: /

  - title: Support Us
    url: /support-us

  - title: About
    url: /about
