permalink: /:year-:month-:day/:title
markdown: rdiscount
# excluding lots because it's now on tumblr
exclude: ["README.md", "CNAME", "LICENSE", "index.html", "feed.xml", "about.md", "code.md", "package.json", "robots.txt", "search.html", "sitemap.txt", "sitemap.xml", "subscribe.md"]

title : MinuteLabs.io
url : http://minutelabs.io
description : "Cool science shown through a combination different media"
version: "0.0.5"
library_path: "/library"

social :
  email : info@minutelabs.io
  github : minutelabsio
  twitter : minutelabsio

limits :
  posts : nil

nav:
  - title: Labs
    url: /

  - title: Subscribe
    url: /subscribe

  - title: About
    url: /about

  - title: Code
    url: /code

  - title: Store
    url: http://dftba.com/artist/60/MinutePhysics

tag_legend:
  desktop: "works on desktop browsers"
  tablet: "works on tablets"
  phone: "works on mobile phones"
  video: "contains video"
  article: "article"


